### ISSUE TITLE
ROM crashes if table contains hstore column

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-sql#140]
It crashes on very early stage, even when there is no relation for given column.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom', git: 'https://github.com/rom-rb/rom.git'
  gem 'rom-sql', git: 'https://github.com/rom-rb/rom-sql.git'
  gem 'pg'
  gem 'minitest'
end

require 'minitest/autorun'

DB = Sequel.connect('postgres://localhost/rom_sql_bug')
DB.run 'CREATE EXTENSION IF NOT EXISTS hstore'
DB.run 'CREATE TABLE IF NOT EXISTS users (id serial primary key, attr hstore);'

class BugTest < Minitest::Test
  def test_aggregated_create
    ROM.container(:sql, 'postgres://localhost/rom_sql_bug')
  end
end
```

```
 1) Error:
BugTest#test_aggregated_create:
ROM::Schema::MissingAttributesError: missing attributes in ROM::Relation::Name(users) schema: :attr
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/schema.rb:324:in `finalize!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-sql-b2621d53ce5f/lib/rom/sql/schema.rb:100:in `finalize!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:54:in `build_relation'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:25:in `block (2 levels) in run!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:24:in `each'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:24:in `block in run!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/relation_registry.rb:6:in `initialize'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:23:in `new'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize/finalize_relations.rb:23:in `run!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize.rb:93:in `load_relations'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/setup/finalize.rb:62:in `run!'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/create_container.rb:33:in `finalize'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/create_container.rb:11:in `initialize'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/create_container.rb:52:in `initialize'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/create_container.rb:57:in `new'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rom-80002e5dd6ca/lib/rom/create_container.rb:57:in `container'
    rom_sql_hstore.rb:24:in `test_aggregated_create'
```

**Comment by Kukunin** [comment]
Check Postgress `json` type - it works fine. Only `hstore` crashes rom

**Comment by solnic** [comment]
@Kukunin we need to add `hstore` to the inferrer and that will fix it, you can always add an attribute yourself, which will also fix it, so you can do it now to workaround this problem

**Comment by Kukunin** [comment]
@solnic this workaround doesn't work, because it crashes on very first line `ROM.container`. It doesn't load relations even - so I can't set attributes

**Comment by solnic** [comment]
``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom', git: 'https://github.com/rom-rb/rom.git', branch: 'master'
  gem 'rom-sql', git: 'https://github.com/rom-rb/rom-sql.git', branch: 'master'
  gem 'pg'
  gem 'minitest'
end

require 'minitest/autorun'

DB = Sequel.connect('postgres://localhost/rom_sql_bug')
DB.run 'CREATE EXTENSION IF NOT EXISTS hstore'
DB.run 'CREATE TABLE IF NOT EXISTS users (id serial primary key, attr hstore);'

class BugTest < Minitest::Test
  def test_aggregated_create
    ROM.container(:sql, 'postgres://localhost/rom_sql_bug') do |c|
      c.relation(:users) do
        schema(infer: :true) do
          attribute :attr, ROM::SQL::Types::Object
        end
      end
    end
  end
end
```

^^ works for me

**Comment by Kukunin** [comment]
Yes, I confirm that workaround works.

**Comment by solnic** [comment]
For now i'll improve exception message so that people know what they need to do. In 1.0.1 we can add support for hstore to inferrers.

**Comment by Kukunin** [comment]
Another question: should ROM investigate table if there is no relation for it? I don't use that table in ROM at all - but ROM requires a valid schema for it

**Comment by flash-gordon** [comment]
I'll add support for hstore
