### ISSUE TITLE
An association alias does not work

### ISSUE THREAD

**Issue by vbyno** [rom-rb/rom-sql#146]
```ruby
#!/usr/bin/env ruby
require "rom-sql"
require "rom-repository"
require "dry-types"

module Relations
  class Users < ROM::Relation[:sql]
    schema(:users, infer: true) do
      associations do
        has_many :articles
      end
    end
  end

  class Articles < ROM::Relation[:sql]
    schema(:articles, infer: true) do
      associations do
        belongs_to :users, as: :author
      end
    end
  end
end

module Repositories
  class Users < ROM::Repository[:users]
    relations :articles

    def create_with_articles(user)
      command(:create, aggregate(:articles)).call(user)
    end
  end
end

config = ROM::Configuration.new(:sql, "sqlite::memory")

config.gateways[:default].tap do |gateway|
  migration = gateway.migration do
    change do
      create_table :users do
        primary_key :id
        column :name, String
      end

      create_table :articles do
        primary_key :id
        column :name, String
        column :autor_id, Integer
      end
    end
  end

  migration.apply gateway.connection, :up
end

config.register_relation Relations::Users
config.register_relation Relations::Articles
container = ROM.container(config)

user_repo = Repositories::Users.new(container)

puts user_repo.create_with_articles(name: 'John', articles: [{name: 'Article 1'}])
```
As a result I get an error:
```
/gems/ruby-2.1.5@interface/gems/sqlite3-1.3.12/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: no such column: articles.user_id (Sequel::DatabaseError)
        from /gems/ruby-2.1.5@interface/gems/sqlite3-1.3.12/lib/sqlite3/database.rb:91:in `new'
        from /gems/ruby-2.1.5@interface/gems/sqlite3-1.3.12/lib/sqlite3/database.rb:91:in `prepare'
        from /gems/ruby-2.1.5@interface/gems/sqlite3-1.3.12/lib/sqlite3/database.rb:264:in `query'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/database/logging.rb:44:in `log_connection_yield'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/adapters/sqlite.rb:187:in `block in _execute'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/adapters/sqlite.rb:130:in `execute'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:970:in `execute'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/adapters/sqlite.rb:322:in `fetch_rows'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:141:in `each'
        from /gems/ruby-2.1.5@interface/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:73:in `columns'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/relation.rb:133:in `columns'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/relation.rb:147:in `selected_columns'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/relation.rb:124:in `header'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/association/one_to_many.rb:18:in `block in call'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/association/one_to_many.rb:47:in `with_keys'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/sql/association/one_to_many.rb:9:in `call'
        from /gems/ruby-2.1.5@interface/gems/rom-sql-0.9.0/lib/rom/plugins/relation/sql/auto_combine.rb:35:in `for_combine'
        from /gems/ruby-2.1.5@interface/gems/rom-support-2.0.0/lib/rom/support/auto_curry.rb:37:in `block (2 levels) in auto_curry'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/relation_proxy.rb:212:in `method_missing'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/relation_proxy/combine.rb:219:in `combine_opts_for_assoc'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/relation_proxy/combine.rb:63:in `block in combine'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/relation_proxy/combine.rb:59:in `each'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/relation_proxy/combine.rb:59:in `combine'
        from /gems/ruby-2.1.5@interface/gems/rom-repository-0.3.1/lib/rom/repository/root.rb:76:in `aggregate'
        from rom-relation_alias.rb:29:in `create_with_articles'
        from rom-relation_alias.rb:61:in `<main>'
```
When I change association `article_id` to `user_id` everything work fine.

**Comment by solnic** [comment]
You can set `foreign_key: :author_id`. I'll fix it in the next bugfix version.

Thanks,
Piotr

**Comment by flash-gordon** [comment]
don't think it's related, but `articles` has `autor_id` field instead of `author_id`

**Comment by vbyno** [comment]
@flash-gordon , thanks for a pointing at the typo.
However, I've updated an environment:
```
rom (3.0.1)
rom-repository (1.0.1)
rom-sql (1.0.0)
```
And retried the next example:
```
#!/usr/bin/env ruby
require "rom-sql"
require "rom-repository"
require "dry-types"

module Relations
  class Users < ROM::Relation[:sql]
    schema(:users, infer: true) do
      associations do
        has_many :articles
      end
    end
  end

  class Articles < ROM::Relation[:sql]
    schema(:articles, infer: true) do
      associations do
        belongs_to :users, as: :author, foreign_key: :author_id
      end
    end
  end
end

module Repositories
  class Users < ROM::Repository[:users]
    relations :articles

    def create_with_articles(user)
      command(:create, aggregate(:articles)).call(user)
    end
  end

  class Articles < ROM::Repository[:articles]
  end
end

config = ROM::Configuration.new(:sql, "sqlite::memory")

config.gateways[:default].tap do |gateway|
  migration = gateway.migration do
    change do
      create_table :users do
        primary_key :id
        column :name, String
      end

      create_table :articles do
        primary_key :id
        column :name, String
        column :author_id, Integer
      end
    end
  end

  migration.apply gateway.connection, :up
end

config.register_relation Relations::Users
config.register_relation Relations::Articles
container = ROM.container(config)

user_repo = Repositories::Users.new(container)
articles_repo = Repositories::Articles.new(container)

user_repo.create_with_articles(name: 'John', articles: [{name: 'Article 1'}])
print articles_repo.articles.last
```
I didn't get an error. Although, the result was:
```
{:id=>1, :name=>"Article 1", :author_id=>nil
```
So, `article` was created, but `author_id` was nil.
It works only if I set
```
create_table :articles do
        primary_key :id
        column :name, String
        foreign_key :author_id, :users
      end
```
or (surprisingly)
```
create_table :articles do
        primary_key :id
        column :name, String
        column :user_id
      end
```
 The last one was unexpected to me as far as I had `belongs_to :users, as: :author, foreign_key: :author_id` in user's relation

**Comment by solnic** [comment]
`has_many :articles, foreign_key: :author_id` is also needed, worked for me:

``` ruby
#<ROM::Struct[User] id=1 name="John" articles=[#<ROM::Struct[Article] id=1 name="Article 1" author_id=1>]>
```

I guess we can come up with some ways of validating association configuration, as it can be tricky.

**Comment by solnic** [comment]
I'm gonna close this. We have run-time associations with config validation + option inference on the [2.0.0 roadmap](https://discuss.rom-rb.org/t/rom-4-0-roadmap-draft/133) so this will be improved eventually.
