### ISSUE TITLE
Timestamp plugin breaks with chained commands

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-sql#152]
When a command has been chained, methods called with input tuples receive all of those tuples, which it does not currently support.

this results in an argument error:

```ruby
ArgumentError - wrong number of arguments (given 2, expected 1):                                                                                                                                         
  rom-sql (1.0.1) lib/rom/sql/plugin/timestamps.rb:99:in `set_timestamps'                                                                                                                                
  rom (3.0.1) lib/rom/command.rb:452:in `block in apply_hooks'                                                                                                                                           
  rom (3.0.1) lib/rom/command.rb:447:in `each'                                                                                                                                                           
  rom (3.0.1) lib/rom/command.rb:447:in `reduce'                                                                                                                                                         
  rom (3.0.1) lib/rom/command.rb:447:in `apply_hooks'                                                                                                                                                    
  rom (3.0.1) lib/rom/command.rb:274:in `call'
```

I'll get some specs around this and try to fix later this evening.

**Comment by flash-gordon** [comment]
@cflipse could use my branch for specs? https://github.com/rom-rb/rom-sql/pull/153 I'm planning to merge it to master once specs are green. Oracle-related features will be added in other PRs, so it won't be long

**Comment by flash-gordon** [comment]
Oh, it works, sweet. I merged the branch so discard my previous comment
