### ISSUE TITLE
Sum does not curry as expected

### ISSUE THREAD

**Issue by mrship** [rom-rb/rom-sql#156]
I'm trying to sum grouped results. I have made this work correctly using the `sum`  repo method below by using sql functions but I would have expected one (or all) of the other 3 methods to also work. I'm pretty sure that in 0.9, the `sum_block` approach worked.

I realise this is because `sum` doesn't return a relation, but a Fixnum. However, it is confusing behaviour (at least to me :).

Any thoughts on making this simpler? i.e. not having to use the SQL functions.

```ruby
#!/usr/bin/env ruby
require 'rom-sql'
require 'rom-repository'
require 'dry-types'

module Types
  include Dry::Types.module
end

rom = ROM.container(:sql, 'sqlite::memory') do |c|
  c.gateways[:default].create_table :opportunities do
    primary_key :id
    column :employee_id, String
    column :value, String
  end

  c.gateways[:default].use_logger(Logger.new($stdout))

  c.relation(:opportunities) do
    schema(:opportunities, infer: false) do
      attribute :id, Types::Int.meta(primary_key: true)
      attribute :employee_id, Types::String
      attribute :value, Types::Int
    end
  end
end

rom.relations[:opportunities].insert value: 100, employee_id: "XYZ"
rom.relations[:opportunities].insert value: 200, employee_id: "XYZ"
rom.relations[:opportunities].insert value: 1000, employee_id: "ABC"
rom.relations[:opportunities].insert value: 2000, employee_id: "ABC"

class OpportunitiesRepo < ROM::Repository[:opportunities]
  def sum(employee_ids)
    opportunities.select { [:employee_id, int::sum(:value).as(:value)] }
      .where(employee_id: employee_ids).group(:employee_id)
  end

  def sum_block(employee_ids)
    opportunities.select(:employee_id).select_append { sum(:value).as(:value) }
      .where(employee_id: employee_ids).group(:employee_id)
  end

  def sum_curry(employee_ids)
    opportunities.sum(:value)
      .where(employee_id: employee_ids).group(:employee_id)
  end

  def sum_end(employee_ids)
    opportunities
      .where(employee_id: employee_ids).group(:employee_id)
      .sum(:value)
  end
end

repo = OpportunitiesRepo.new(rom)

# SELECT `employee_id`, SUM(`value`) AS 'value' FROM `opportunities` WHERE (`employee_id` IN ('XYZ', 'ABC')) GROUP BY `employee_id` ORDER BY `opportunities`.`id`
# [#<ROM::Struct[Opportunity] employee_id="XYZ" value=300>, #<ROM::Struct[Opportunity] employee_id="ABC" value=3000>]
puts repo.sum(["XYZ", "ABC"]).to_a.inspect

# puts repo.sum_block(["XYZ", "ABC"]).to_a.inspect
# rom-sql-1.0.1/lib/rom/sql/projection_dsl.rb:36:in `method_missing': undefined method `sum' for #<ROM::SQL::ProjectionDSL:0x007f8883335a28> (NoMethodError)

# puts repo.sum_curry(["XYZ", "ABC"]).to_a.inspect
# I, [2017-02-15T22:09:39.356601 #88485]  INFO -- : (0.000077s) SELECT sum(`value`) AS 'sum' FROM `opportunities` LIMIT 1
# `sum_curry': undefined method `where' for 3300:Fixnum (NoMethodError)

# puts repo.sum_end(["XYZ", "ABC"]).to_a.inspect
# ./sum.rb:67:in `<main>': undefined method `to_a' for 2200:Fixnum (NoMethodError)
```

**Comment by solnic** [comment]
You need to specify return type for any function that you use in select, so `sum { int::sum(:value).as(:value) }` should work fine

**Comment by mrship** [comment]
OK, I see. Thanks for the clarification.
