### ISSUE TITLE
wrap_parent not using custom correct foreign key

### ISSUE THREAD

**Issue by mrship** [rom-rb/rom-sql#186]
We are trying a simple `wrap_parent` call with a custom foreign key and the generated query does not respect the specified foreign_key and we get this error:

```
ERROR -- : SQLite3::SQLException: no such column: frameworks.country_id: SELECT `frameworks`.`id`, `frameworks`.`country_iso`, `countries`.`iso` AS 'countries_iso', `countries`.`name` AS 'countries_name' FROM `frameworks` INNER JOIN `countries` ON (`countries`.`iso` = `frameworks`.`country_id`) ORDER BY `frameworks`.`id`
```

Here's the test case:

```ruby
#!/usr/bin/env ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'dry-types'
  gem 'sqlite3'
end

require 'rom-sql'
require 'rom-repository'
require 'dry-types'

module Types
  include Dry::Types.module
end

rom = ROM.container(:sql, 'sqlite::memory') do |c|
  c.gateways[:default].create_table :countries do
    column :iso, String
    column :name, String
  end

  c.gateways[:default].create_table :frameworks do
    column :id, Integer
    column :country_iso, String
  end

  c.gateways[:default].use_logger(Logger.new($stdout))

  c.relation(:countries) do
    schema(infer: false) do
      attribute :iso, Types::String.meta(primary_key: true)
      attribute :name, Types::String
    end
  end

  c.relation(:frameworks) do
    schema(:frameworks, infer: false) do
      attribute :id, Types::Int.meta(primary_key: true)
      attribute :country_iso, Types::String
      associations do
        belongs_to :countries, as: :country, foreign_key: :country_iso
      end
    end
  end
end

rom.relations[:countries].insert(iso: "GB", name: "United Kingdom")
rom.relations[:frameworks].insert(country_iso: "GB")

class FrameworkRepo < ROM::Repository[:frameworks]
  relations :countries

  def query
    frameworks
      .wrap_parent(country: countries)
      .to_a
  end
end

repo = FrameworkRepo.new(rom)

puts repo.query.to_a.inspect
```

Are we doing something wrong in how we're specifying the foreign_key?

**Comment by solnic** [comment]
Please try:

``` ruby
frameworks.wrap_parent(:country).to_a
```

**Comment by mrship** [comment]
If I try that, I get: 
```
/Users/shipmana/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-repository-1.3.1/lib/rom/repository/relation_proxy/wrap.rb:39:in `wrap_parent': undefined method `each_with_object' for :country:Symbol (NoMethodError)
	from ./wrap_parent.rb:60:in `query'
	from ./wrap_parent.rb:67:in `<main>'
```

**Comment by solnic** [comment]
Gah, sorry, I meant `frameworks.wrap(:count).to_a`

**Comment by mrship** [comment]
Yay! That works. (well `frameworks.wrap(:country).to_a`, but it does work)

```
I, [2017-04-20T12:08:04.674853 #35650]  INFO -- : (0.000204s) SELECT `frameworks`.`id`, `frameworks`.`country_iso`, `countries`.`iso` AS 'countries_iso', `countries`.`name` AS 'countries_name' FROM `frameworks` INNER JOIN `countries` ON (`frameworks`.`country_iso` = `countries`.`iso`) ORDER BY `frameworks`.`id`
[#<ROM::Struct[Framework] id=nil country_iso="GB" country=#<ROM::Struct[Country] iso="GB" name="United Kingdom">>]
```

**Comment by solnic** [comment]
@mrship ok cool, I added support for associations to `wrap` recently so I guess it's not clearly documented. `wrap_parent` will be probably removed anyway as we're moving to associations and ad-hoc composition won't be supported in 2.0

**Comment by solnic** [comment]
Closing this as it works with `wrap`
