### ISSUE TITLE
Dealing with Postgres ranges.

### ISSUE THREAD

**Issue by cutalion** [rom-rb/rom-sql#231]
How to deal with PG ranges?

I'm trying to connect to existing database (tried with and without extensions)
```
Sequel.extension(:pg_range)
Sequle.extension(:pg_range_ops)
ROM.container(:sql, 'postgres://localhost/my_database', extensions: [:pg_range]) 
```

There is a table `announcements` with the `tstzrange` field named `when`.

And I always get an error 
```
     ROM::Schema::MissingAttributesError:
       missing attributes in ROM::Relation::Name(announcements) schema: :when
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/schema.rb:324:in `finalize!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-sql-1.3.3/lib/rom/sql/schema.rb:109:in `finalize!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:57:in `build_relation'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:28:in `block (2 levels) in run!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:27:in `each'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:27:in `block in run!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/relation_registry.rb:6:in `initialize'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:26:in `new'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize/finalize_relations.rb:26:in `run!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize.rb:99:in `load_relations'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/setup/finalize.rb:65:in `run!'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/create_container.rb:34:in `finalize'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/create_container.rb:11:in `initialize'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/create_container.rb:53:in `initialize'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/create_container.rb:58:in `new'
     # /home/cutalion/.rvm/gems/ruby-2.3.3/gems/rom-3.3.1/lib/rom/create_container.rb:58:in `container'
```

It's seems very odd, because the following code works.

```
$ pry
[1] pry(main)> require 'sequel'
=> true
[2] pry(main)> DB = Sequel.connect("postgres://localhost/my_database")
=> #<Sequel::Postgres::Database: "postgres://cutalion@localhost/my_database">   
[3] pry(main)> DB.extension(:pg_range)
=> #<Sequel::Postgres::Database: "postgres://cutalion@localhost/my_database">
[4] pry(main)> DB[:announcements].first[:when]
=> #<Sequel::Postgres::PGRange:0x000000024e5488
 @begin=2017-04-15 06:00:00 +0300,
 @db_type="tstzrange",
 @empty=false,
 @end=2017-04-15 14:00:00 +0300,
 @exclude_begin=false,
 @exclude_end=false>
```

Is there a way to work with range types in postgres?

**Comment by flash-gordon** [comment]
@cutalion you need to define this attribute explicitly because rom cannot infer it automatically. I gotta admit the error message is misleading here. 

Try this
```ruby
schema(infer: true) do 
  attribute :announcements, Types::Any
end
```

^this will return you the type Sequel returns for range columns, i.e. `Sequel::Postgres::PGRange` (given that you loaded the `pg_range` extension).

**Comment by cutalion** [comment]
@flash-gordon thanks, I'll try that! Though I've already defined `PGRange` type in my project
```ruby
PGRange = ROM::SQL::Types.Definition(Sequel::Postgres::PGRange)
```

**Comment by flash-gordon** [comment]
yeah, this is fine, you can use it like that, `Any` is just a placeholder that you can use right away, more specific types are better, no doubt

**Comment by flash-gordon** [comment]
I created a separate ticket for range https://github.com/rom-rb/rom-sql/issues/234 and fixed the message you posted to make it less confusing so I shall close this one
