### ISSUE TITLE
schema infer fails with pg_enum in primary key

### ISSUE THREAD

**Issue by vsuhachev** [rom-rb/rom-sql#254]
```ruby
ROM::SQL.migration do
  change do
    extension :pg_enum
    create_enum :my_enum, %w(one two)
    create_table :example do
      column :my_attr, :my_enum
      primary_key [:my_attr]
    end
  end
end
```

```ruby
class Example < ROM::Relation[:sql]
  schema(:example, infer: true)
end
```

**Comment by solnic** [comment]
Could you include a stacktrace too?

**Comment by vsuhachev** [comment]
```
bundler: failed to load command: bin/console (bin/console)
NoMethodError: undefined method `meta' for nil:NilClass
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/extensions/postgres/type_builder.rb:42:in `map_pk_type'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/type_builder.rb:40:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/attributes_inferrer.rb:26:in `block in call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/attributes_inferrer.rb:25:in `map'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/attributes_inferrer.rb:25:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:17:in `block in <class:Inferrer>'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/schema/inferrer.rb:40:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:35:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/schema.rb:361:in `finalize_attributes!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-sql-2.0.0/lib/rom/sql/schema.rb:146:in `finalize_attributes!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/schema.rb:56:in `block in <class:Schema>'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/support/notifications.rb:131:in `trigger'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/support/notifications.rb:69:in `block in trigger'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/support/notifications.rb:68:in `each'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/support/notifications.rb:68:in `trigger'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize/finalize_relations.rb:82:in `build_relation'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize/finalize_relations.rb:48:in `block (2 levels) in run!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize/finalize_relations.rb:31:in `each'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize/finalize_relations.rb:31:in `block in run!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/relation_registry.rb:9:in `initialize'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/registry.rb:27:in `new'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/registry.rb:27:in `new'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize/finalize_relations.rb:30:in `run!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize.rb:86:in `load_relations'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/setup/finalize.rb:62:in `run!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/create_container.rb:38:in `finalize'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/create_container.rb:14:in `initialize'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/create_container.rb:59:in `initialize'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/create_container.rb:65:in `new'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/rom-core-4.0.1/lib/rom/create_container.rb:65:in `container'
  /home/vs/code/rb/dry/sklad/system/boot/persistence.rb:35:in `block (2 levels) in <top (required)>'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/lifecycle.rb:119:in `trigger!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/lifecycle.rb:84:in `start'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/lifecycle.rb:56:in `block in call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/lifecycle.rb:54:in `each'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/lifecycle.rb:54:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/components/bootable.rb:96:in `start'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:77:in `block (2 levels) in start'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:64:in `block (2 levels) in init'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:93:in `block in call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:117:in `with_component'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:88:in `call'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:62:in `block in init'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:117:in `with_component'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:61:in `init'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:76:in `block in start'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:117:in `with_component'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:73:in `start'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:53:in `block in finalize!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter/component_registry.rb:14:in `each'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter/component_registry.rb:14:in `each'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/booter.rb:52:in `finalize!'
  /home/vs/.rvm/gems/ruby-2.4.1@global/gems/dry-system-0.8.1/lib/dry/system/container.rb:295:in `finalize!'
  /home/vs/code/rb/dry/sklad/system/boot.rb:8:in `<top (required)>'
  bin/console:5:in `require_relative'
  bin/console:5:in `<top (required)>'
```

**Comment by vsuhachev** [comment]
`map_pk_type` in pg extension calls `map_type` without `kw` and fail to find type for enum
