### ISSUE TITLE
has-many :through loses parent association conditions

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-sql#259]
(I'll put together a repo script for this later, but I want to get this noted now:)

When a join table has a non-default set of join conditions, a `has_many :through` appears to be ignoring those conditions:

```
class ProductRelation < ROM::Relation[:sql]
  schema :products, infer: true do
    associations do
        has_many :attachments, foreign_key: :parent_id
        has_many :documents, through :attachments
    end
  end
end
```

```
irb(main):008:0> ROM.env.relations[:products].combine(:documents).limit(1).one
KeyError: :product_id attribute doesn't exist in attachments schema
        from (irb):8
irb(main):010:0> ROM.env.relations[:products].associations[:documents].join_keys
KeyError: :product_id attribute doesn't exist in attachments schema
        from (irb):10
```

**Comment by cflipse** [comment]
Repro script:
https://gist.github.com/cflipse/8545ff9dbd7cffa1c48f7e7b7b5dab73

puts output:
```
{:id=>1, :name=>"test 1", :attachments=>[{:id=>1, :document_id=>100, :test_id=>1}]}
{:id=>1, :document_id=>100, :test_id=>1, :document=>{:id=>100, :name=>"test document"}}
/home/flip/.gem/ruby/2.4.1/gems/rom-core-4.0.1/lib/rom/schema.rb:197:in `[]': :product_id attribute doesn't exist in attachments schema (KeyError)
	from /home/flip/.gem/ruby/2.4.1/gems/rom-core-4.0.1/lib/rom/schema.rb:211:in `block in project'
```

**Comment by solnic** [comment]
Actually, you need to define custom fk on the `:documents` assoc, so:

``` ruby
has_many :documents, through :attachments, foreign_key: :parent_id`
```
