### ISSUE TITLE
:users doesn't exist in ROM::RelationRegistry registry

### ISSUE THREAD

**Issue by TLINDEN** [rom-rb/rom-sql#268]
Hello,

I'm totally new to ROM. I am unable to get the [example from](http://rom-rb.org/4.0/learn/repositories/reading-simple-objects/#full-example) to work.

The error I'm getting is:
```
% ruby users.rb 
/home/tom/.rvm/gems/ruby-2.3.1/gems/rom-core-4.1.0/lib/rom/registry.rb:76:in `block in fetch': :users doesn't exist in ROM::RelationRegistry registry (ROM::ElementNotFoundError)
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-core-4.1.0/lib/rom/registry.rb:73:in `fetch'
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-core-4.1.0/lib/rom/registry.rb:73:in `fetch'
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-repository-2.0.1/lib/rom/repository/relation_reader.rb:15:in `set_relation'
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-repository-2.0.1/lib/rom/repository/root.rb:61:in `initialize'
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-repository-2.0.1/lib/rom/repository/class_interface.rb:42:in `new'
	from /home/tom/.rvm/gems/ruby-2.3.1/gems/rom-repository-2.0.1/lib/rom/repository/class_interface.rb:42:in `new'
	from users.rb:23:in `<main>'
```
This is the list of gems installed:
```
bigdecimal (1.2.8)
bundler-unload (1.0.2)
concurrent-ruby (1.0.5)
did_you_mean (1.0.0)
dry-configurable (0.7.0)
dry-container (0.6.0)
dry-core (0.4.1)
dry-equalizer (0.2.0)
dry-inflector (0.1.1)
dry-initializer (2.3.0)
dry-logic (0.4.2)
dry-struct (0.4.0)
dry-types (0.12.2)
executable-hooks (1.3.2)
gem-wrappers (1.4.0, 1.2.7)
ice_nine (0.11.2)
inflecto (0.0.2)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
rom (4.1.0)
rom-changeset (1.0.1)
rom-core (4.1.0)
rom-mapper (1.1.0)
rom-repository (2.0.1)
rom-sql (2.3.0)
rvm (1.11.3.9)
sequel (5.2.0)
sqlite3 (1.3.13)
test-unit (3.1.5)
transproc (1.0.2)
```

Any idea what's wrong here?

thanks,
Tom

**Comment by v-kolesnikov** [comment]
Hi, @TLINDEN !

You must explicitly define all relations witch you want to use, so try to add following line in your ROM configuration: `config.relation(:users)`.

**Comment by TLINDEN** [comment]
works. Thanks!
