### ISSUE TITLE
Caching the Sequel::Model on the Class instance breaks for multiple environments

### ISSUE THREAD

**Issue by endash** [rom-rb/rom-sql#39]
Things break when you finalize the second time:

```
/Users/chris/.rvm/gems/ruby-2.2.3/gems/sequel-4.26.0/lib/sequel/model/base.rb:1097:in `simple_table='
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/sequel-4.26.0/lib/sequel/model/base.rb:815:in `convert_input_dataset'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/sequel-4.26.0/lib/sequel/model/base.rb:686:in `set_dataset'
    /Users/chris/.rvm/gems/ruby-2.2.3/bundler/gems/rom-sql-47dcd189f797/lib/rom/sql/relation/class_methods.rb:100:in `finalize'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/relation/class_interface.rb:181:in `block in registry'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/relation/class_interface.rb:180:in `each_value'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/relation/class_interface.rb:180:in `registry'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/setup/finalize.rb:86:in `load_relations'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/setup/finalize.rb:58:in `run!'
    /Users/chris/.rvm/gems/ruby-2.2.3/gems/rom-0.9.1/lib/rom/setup.rb:95:in `finalize'
```

**Comment by solnic** [comment]
Small update: this functionality is now a plugin called `assoc_macros` and personally I don't plan to support this feature.
