### ISSUE TITLE
schema breaks on code reload

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-sql#93]
Working in a rails console, I added a new `associations` entry to a schema block, and reloaded.  Exception thrown:

```
irb(main):003:0> reload!
Reloading...
  ROM[postgres] (0.1ms)  SET standard_conforming_strings = ON  
# ... lots of logging things elided
RuntimeError: can't modify frozen ROM::SQL::Schema
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/schema.rb:81:in `finalize!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/schema.rb:24:in `finalize!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:53:in `build_relation'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:25:in `block (2 levels) in run!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:24:in `each'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:24:in `block in run!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/relation_registry.rb:6:in `initialize'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:23:in `new'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize/finalize_relations.rb:23:in `run!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize.rb:93:in `load_relations'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/setup/finalize.rb:62:in `run!'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/create_container.rb:35:in `finalize'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/create_container.rb:13:in `initialize'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/create_container.rb:54:in `initialize'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/create_container.rb:59:in `new'
        from /home/flip/.gem/ruby/2.3.0/gems/rom-2.0.0/lib/rom/create_container.rb:59:in `container'
... 28 levels...
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:99:in `run!'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:113:in `run!'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:48:in `block (2 levels) in reload!'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:46:in `tap'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:46:in `block in reload!'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
        from /home/flip/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:45:in `reload!'
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/console/app.rb:32:in `reload!'
        from (irb):3
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/flip/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'irb(main):004:0> 
```

**Comment by solnic** [comment]
We can add a hack to rom-rails that will prevent freezing in dev mode

**Comment by cflipse** [comment]
Digging some, it seems more likely that the schema objects are being preserved across reloads, rather than thrown out, as should probably be done.

Still backtracing

**Comment by solnic** [comment]
schemas are static configurations stored as part of the relation class state under `@schema` class ivar

**Comment by cflipse** [comment]
In theory, outside of the code reload stuff, I should be able to reuse the configuration to create two containers; I think that might not be the case here .... (checks) ...

Yep.  I'm going to say that this is actually a bug in core; closing and moving.

**Comment by cflipse** [comment]
see https://github.com/rom-rb/rom/issues/356
